version: "3"
services:
  redmine:
    image: redmine:latest
    container_name: redmine
    ports:
      - "13000:3000"
    environment:
      - TZ=Asia/Seoul
      - REDMINE_DB_POSTGRES=postgres
      - REDMINE_DB_DATABASE=redmine
      - REDMINE_DB_USERNAME=postgres
      - REDMINE_DB_PASSWORD=postgres    
    volumes:
      - redmine_data:/usr/src/redmine/files
    networks:
      - tool_chain
    restart: always

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "18080:8080"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - tool_chain
    restart: always

  ssh-agent:
    image: jenkins/ssh-agent
    environment:
      - TZ=Asia/Seoul
    networks:
      - tool_chain
    restart: always

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "19000:9000"
    environment:
      - TZ=Asia/Seoul
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
      - SONAR_JDBC_USERNAME=postgres
      - SONAR_JDBC_PASSWORD=postgres
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_temp:/opt/sonarqube/temp
    networks:
      - tool_chain
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tool_chain
    restart: always

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "18082:8080"
    networks:
      - tool_chain
    restart: always

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    ports:
      - "14000:3000"
      - "1222:22"
    environment:
      - TZ=Asia/Seoul
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=postgres
      - GITEA__database__PASSWD=postgres
    restart: always
    volumes:
      - gitea_data:/var/lib/gitea
      - gitea_config:/etc/gitea
      - gitea_logs:/var/log/gitea
    networks:
      - tool_chain

  lhci:
    image: patrickhulce/lhci-server:latest
    container_name: lhci
    ports:
      - "19003:9003"
    environment:
      - TZ=Asia/Seoul
      - LHCI_STORAGE__SQL_DATABASE_URL=postgres://postgres:postgres@postgres:5432/lhci
      - LHCI_PORT=9003
    volumes:
      - lhci_data:/data
      - ./lighthouserc.json:/app/lighthouserc.json
    networks:
      - tool_chain
    restart: always

networks:
  tool_chain:
    driver: bridge

volumes:
  redmine_data:
  jenkins_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_temp:
  postgres_data:
  gitea_data:
  gitea_config:
  gitea_logs:
  lhci_data:
